# Generated by Django 5.1.4 on 2024-12-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pb', '0002_pastebin_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastebin',
            name='id',
            field=models.TextField(default='', primary_key=True, serialize=False),
        ),
    ]
